# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "CalculatorRequest" do
    optional :number1, :double, 1
    optional :number2, :double, 2
    optional :operation, :enum, 3, "CalculatorRequest.OperationType"
  end
  add_enum "CalculatorRequest.OperationType" do
    value :ADD, 0
    value :SUBTRACT, 1
    value :MULTIPLY, 2
    value :DIVIDE, 3
  end
  add_message "CalculatorResponse" do
    optional :result, :double, 1
  end
end

CalculatorRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("CalculatorRequest").msgclass
CalculatorRequest::OperationType = Google::Protobuf::DescriptorPool.generated_pool.lookup("CalculatorRequest.OperationType").enummodule
CalculatorResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("CalculatorResponse").msgclass
