# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "HelloRequest" do
    optional :name, :string, 1
  end
  add_message "HelloReply" do
    optional :message, :string, 1
  end
end

HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloRequest").msgclass
HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("HelloReply").msgclass
