// flow-typed signature: a8e88e9cf3da10c9f8f5fdabb40a201d
// flow-typed version: <<STUB>>/element-ui_v^1.4.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'element-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'element-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'element-ui/lib/alert' {
  declare module.exports: any;
}

declare module 'element-ui/lib/autocomplete' {
  declare module.exports: any;
}

declare module 'element-ui/lib/badge' {
  declare module.exports: any;
}

declare module 'element-ui/lib/breadcrumb-item' {
  declare module.exports: any;
}

declare module 'element-ui/lib/breadcrumb' {
  declare module.exports: any;
}

declare module 'element-ui/lib/button-group' {
  declare module.exports: any;
}

declare module 'element-ui/lib/button' {
  declare module.exports: any;
}

declare module 'element-ui/lib/card' {
  declare module.exports: any;
}

declare module 'element-ui/lib/carousel-item' {
  declare module.exports: any;
}

declare module 'element-ui/lib/carousel' {
  declare module.exports: any;
}

declare module 'element-ui/lib/cascader' {
  declare module.exports: any;
}

declare module 'element-ui/lib/checkbox-button' {
  declare module.exports: any;
}

declare module 'element-ui/lib/checkbox-group' {
  declare module.exports: any;
}

declare module 'element-ui/lib/checkbox' {
  declare module.exports: any;
}

declare module 'element-ui/lib/col' {
  declare module.exports: any;
}

declare module 'element-ui/lib/collapse-item' {
  declare module.exports: any;
}

declare module 'element-ui/lib/collapse' {
  declare module.exports: any;
}

declare module 'element-ui/lib/color-picker' {
  declare module.exports: any;
}

declare module 'element-ui/lib/date-picker' {
  declare module.exports: any;
}

declare module 'element-ui/lib/dialog' {
  declare module.exports: any;
}

declare module 'element-ui/lib/dropdown-item' {
  declare module.exports: any;
}

declare module 'element-ui/lib/dropdown-menu' {
  declare module.exports: any;
}

declare module 'element-ui/lib/dropdown' {
  declare module.exports: any;
}

declare module 'element-ui/lib/element-ui.common' {
  declare module.exports: any;
}

declare module 'element-ui/lib/form-item' {
  declare module.exports: any;
}

declare module 'element-ui/lib/form' {
  declare module.exports: any;
}

declare module 'element-ui/lib/icon' {
  declare module.exports: any;
}

declare module 'element-ui/lib/index' {
  declare module.exports: any;
}

declare module 'element-ui/lib/input-number' {
  declare module.exports: any;
}

declare module 'element-ui/lib/input' {
  declare module.exports: any;
}

declare module 'element-ui/lib/loading' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/format' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/index' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/af-ZA' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/ar' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/bg' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/ca' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/cz' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/da' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/de' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/ee' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/el' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/en' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/es' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/fa' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/fi' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/fr' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/id' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/it' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/ja' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/ko' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/lv' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/nb-NO' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/nl' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/pl' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/pt-br' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/pt' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/ru-RU' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/sk' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/sl' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/sv-SE' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/ta' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/th' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/tk' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/tr-TR' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/ua' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/vi' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/zh-CN' {
  declare module.exports: any;
}

declare module 'element-ui/lib/locale/lang/zh-TW' {
  declare module.exports: any;
}

declare module 'element-ui/lib/menu-item-group' {
  declare module.exports: any;
}

declare module 'element-ui/lib/menu-item' {
  declare module.exports: any;
}

declare module 'element-ui/lib/menu' {
  declare module.exports: any;
}

declare module 'element-ui/lib/message-box' {
  declare module.exports: any;
}

declare module 'element-ui/lib/message' {
  declare module.exports: any;
}

declare module 'element-ui/lib/mixins/emitter' {
  declare module.exports: any;
}

declare module 'element-ui/lib/mixins/locale' {
  declare module.exports: any;
}

declare module 'element-ui/lib/mixins/migrating' {
  declare module.exports: any;
}

declare module 'element-ui/lib/notification' {
  declare module.exports: any;
}

declare module 'element-ui/lib/option-group' {
  declare module.exports: any;
}

declare module 'element-ui/lib/option' {
  declare module.exports: any;
}

declare module 'element-ui/lib/pagination' {
  declare module.exports: any;
}

declare module 'element-ui/lib/popover' {
  declare module.exports: any;
}

declare module 'element-ui/lib/progress' {
  declare module.exports: any;
}

declare module 'element-ui/lib/radio-button' {
  declare module.exports: any;
}

declare module 'element-ui/lib/radio-group' {
  declare module.exports: any;
}

declare module 'element-ui/lib/radio' {
  declare module.exports: any;
}

declare module 'element-ui/lib/rate' {
  declare module.exports: any;
}

declare module 'element-ui/lib/row' {
  declare module.exports: any;
}

declare module 'element-ui/lib/scrollbar' {
  declare module.exports: any;
}

declare module 'element-ui/lib/select' {
  declare module.exports: any;
}

declare module 'element-ui/lib/slider' {
  declare module.exports: any;
}

declare module 'element-ui/lib/spinner' {
  declare module.exports: any;
}

declare module 'element-ui/lib/step' {
  declare module.exports: any;
}

declare module 'element-ui/lib/steps' {
  declare module.exports: any;
}

declare module 'element-ui/lib/submenu' {
  declare module.exports: any;
}

declare module 'element-ui/lib/switch' {
  declare module.exports: any;
}

declare module 'element-ui/lib/tab-pane' {
  declare module.exports: any;
}

declare module 'element-ui/lib/table-column' {
  declare module.exports: any;
}

declare module 'element-ui/lib/table' {
  declare module.exports: any;
}

declare module 'element-ui/lib/tabs' {
  declare module.exports: any;
}

declare module 'element-ui/lib/tag' {
  declare module.exports: any;
}

declare module 'element-ui/lib/time-picker' {
  declare module.exports: any;
}

declare module 'element-ui/lib/time-select' {
  declare module.exports: any;
}

declare module 'element-ui/lib/tooltip' {
  declare module.exports: any;
}

declare module 'element-ui/lib/transfer' {
  declare module.exports: any;
}

declare module 'element-ui/lib/transitions/collapse-transition' {
  declare module.exports: any;
}

declare module 'element-ui/lib/tree' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/af-ZA' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/ar' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/bg' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/ca' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/cz' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/da' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/de' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/ee' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/el' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/en' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/es' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/fa' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/fi' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/fr' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/id' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/it' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/ja' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/ko' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/lv' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/nb-NO' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/nl' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/pl' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/pt-br' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/pt' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/ru-RU' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/sk' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/sl' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/sv-SE' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/ta' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/th' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/tk' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/tr-TR' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/ua' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/vi' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/zh-CN' {
  declare module.exports: any;
}

declare module 'element-ui/lib/umd/locale/zh-TW' {
  declare module.exports: any;
}

declare module 'element-ui/lib/upload' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/clickoutside' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/date' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/dom' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/merge' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/popper' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/popup/index' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/popup/popup-manager' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/resize-event' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/scroll-into-view' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/scrollbar-width' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/shared' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/sync' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/util' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/vdom' {
  declare module.exports: any;
}

declare module 'element-ui/lib/utils/vue-popper' {
  declare module.exports: any;
}

declare module 'element-ui/packages/alert/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/autocomplete/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/badge/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/breadcrumb-item/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/breadcrumb/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/button-group/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/button/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/card/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/carousel-item/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/carousel/_index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/carousel/cooking.conf' {
  declare module.exports: any;
}

declare module 'element-ui/packages/carousel/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/cascader/cooking.conf' {
  declare module.exports: any;
}

declare module 'element-ui/packages/cascader/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/checkbox-button/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/checkbox-group/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/checkbox/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/col/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/col/src/col' {
  declare module.exports: any;
}

declare module 'element-ui/packages/collapse-item/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/collapse/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/color-picker/cooking.conf' {
  declare module.exports: any;
}

declare module 'element-ui/packages/color-picker/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/color-picker/src/color' {
  declare module.exports: any;
}

declare module 'element-ui/packages/color-picker/src/draggable' {
  declare module.exports: any;
}

declare module 'element-ui/packages/date-picker/_index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/date-picker/cooking.conf' {
  declare module.exports: any;
}

declare module 'element-ui/packages/date-picker/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/date-picker/src/picker/date-picker' {
  declare module.exports: any;
}

declare module 'element-ui/packages/date-picker/src/picker/time-picker' {
  declare module.exports: any;
}

declare module 'element-ui/packages/date-picker/src/picker/time-select' {
  declare module.exports: any;
}

declare module 'element-ui/packages/date-picker/src/util/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/dialog/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/dropdown-item/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/dropdown-menu/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/dropdown/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/form-item/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/form/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/icon/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/input-number/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/input/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/input/src/calcTextareaHeight' {
  declare module.exports: any;
}

declare module 'element-ui/packages/loading/cooking.conf' {
  declare module.exports: any;
}

declare module 'element-ui/packages/loading/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/loading/src/directive' {
  declare module.exports: any;
}

declare module 'element-ui/packages/loading/src/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/menu-item-group/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/menu-item/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/menu/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/menu/src/menu-mixin' {
  declare module.exports: any;
}

declare module 'element-ui/packages/message-box/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/message-box/src/main' {
  declare module.exports: any;
}

declare module 'element-ui/packages/message/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/message/src/main' {
  declare module.exports: any;
}

declare module 'element-ui/packages/notification/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/notification/src/main' {
  declare module.exports: any;
}

declare module 'element-ui/packages/option-group/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/option/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/pagination/cooking.conf' {
  declare module.exports: any;
}

declare module 'element-ui/packages/pagination/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/pagination/src/pagination' {
  declare module.exports: any;
}

declare module 'element-ui/packages/popover/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/popover/src/directive' {
  declare module.exports: any;
}

declare module 'element-ui/packages/progress/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/radio-button/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/radio-group/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/radio/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/rate/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/row/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/row/src/row' {
  declare module.exports: any;
}

declare module 'element-ui/packages/scrollbar/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/scrollbar/src/bar' {
  declare module.exports: any;
}

declare module 'element-ui/packages/scrollbar/src/main' {
  declare module.exports: any;
}

declare module 'element-ui/packages/scrollbar/src/util' {
  declare module.exports: any;
}

declare module 'element-ui/packages/select/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/slider/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/spinner/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/step/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/steps/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/submenu/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/switch/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tab-pane/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table-column/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/_index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/cooking.conf' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/src/dropdown' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/src/table-body' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/src/table-column' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/src/table-footer' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/src/table-header' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/src/table-layout' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/src/table-store' {
  declare module.exports: any;
}

declare module 'element-ui/packages/table/src/util' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tabs/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tag/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/time-picker/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/time-select/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tooltip/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tooltip/src/main' {
  declare module.exports: any;
}

declare module 'element-ui/packages/transfer/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tree/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tree/src/model/node' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tree/src/model/tree-store' {
  declare module.exports: any;
}

declare module 'element-ui/packages/tree/src/model/util' {
  declare module.exports: any;
}

declare module 'element-ui/packages/upload/cooking.conf' {
  declare module.exports: any;
}

declare module 'element-ui/packages/upload/index' {
  declare module.exports: any;
}

declare module 'element-ui/packages/upload/src/ajax' {
  declare module.exports: any;
}

declare module 'element-ui/src/index' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/format' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/index' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/af-ZA' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/ar' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/bg' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/ca' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/cz' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/da' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/de' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/ee' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/el' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/en' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/es' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/fa' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/fi' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/fr' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/id' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/it' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/ja' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/ko' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/lv' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/nb-NO' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/nl' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/pl' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/pt-br' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/pt' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/ru-RU' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/sk' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/sl' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/sv-SE' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/ta' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/th' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/tk' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/tr-TR' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/ua' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/vi' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/zh-CN' {
  declare module.exports: any;
}

declare module 'element-ui/src/locale/lang/zh-TW' {
  declare module.exports: any;
}

declare module 'element-ui/src/mixins/emitter' {
  declare module.exports: any;
}

declare module 'element-ui/src/mixins/locale' {
  declare module.exports: any;
}

declare module 'element-ui/src/mixins/migrating' {
  declare module.exports: any;
}

declare module 'element-ui/src/transitions/collapse-transition' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/clickoutside' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/date' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/dom' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/merge' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/popper' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/popup/index' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/popup/popup-manager' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/resize-event' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/scroll-into-view' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/scrollbar-width' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/shared' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/sync' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/util' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/vdom' {
  declare module.exports: any;
}

declare module 'element-ui/src/utils/vue-popper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'element-ui/lib/alert.js' {
  declare module.exports: $Exports<'element-ui/lib/alert'>;
}
declare module 'element-ui/lib/autocomplete.js' {
  declare module.exports: $Exports<'element-ui/lib/autocomplete'>;
}
declare module 'element-ui/lib/badge.js' {
  declare module.exports: $Exports<'element-ui/lib/badge'>;
}
declare module 'element-ui/lib/breadcrumb-item.js' {
  declare module.exports: $Exports<'element-ui/lib/breadcrumb-item'>;
}
declare module 'element-ui/lib/breadcrumb.js' {
  declare module.exports: $Exports<'element-ui/lib/breadcrumb'>;
}
declare module 'element-ui/lib/button-group.js' {
  declare module.exports: $Exports<'element-ui/lib/button-group'>;
}
declare module 'element-ui/lib/button.js' {
  declare module.exports: $Exports<'element-ui/lib/button'>;
}
declare module 'element-ui/lib/card.js' {
  declare module.exports: $Exports<'element-ui/lib/card'>;
}
declare module 'element-ui/lib/carousel-item.js' {
  declare module.exports: $Exports<'element-ui/lib/carousel-item'>;
}
declare module 'element-ui/lib/carousel.js' {
  declare module.exports: $Exports<'element-ui/lib/carousel'>;
}
declare module 'element-ui/lib/cascader.js' {
  declare module.exports: $Exports<'element-ui/lib/cascader'>;
}
declare module 'element-ui/lib/checkbox-button.js' {
  declare module.exports: $Exports<'element-ui/lib/checkbox-button'>;
}
declare module 'element-ui/lib/checkbox-group.js' {
  declare module.exports: $Exports<'element-ui/lib/checkbox-group'>;
}
declare module 'element-ui/lib/checkbox.js' {
  declare module.exports: $Exports<'element-ui/lib/checkbox'>;
}
declare module 'element-ui/lib/col.js' {
  declare module.exports: $Exports<'element-ui/lib/col'>;
}
declare module 'element-ui/lib/collapse-item.js' {
  declare module.exports: $Exports<'element-ui/lib/collapse-item'>;
}
declare module 'element-ui/lib/collapse.js' {
  declare module.exports: $Exports<'element-ui/lib/collapse'>;
}
declare module 'element-ui/lib/color-picker.js' {
  declare module.exports: $Exports<'element-ui/lib/color-picker'>;
}
declare module 'element-ui/lib/date-picker.js' {
  declare module.exports: $Exports<'element-ui/lib/date-picker'>;
}
declare module 'element-ui/lib/dialog.js' {
  declare module.exports: $Exports<'element-ui/lib/dialog'>;
}
declare module 'element-ui/lib/dropdown-item.js' {
  declare module.exports: $Exports<'element-ui/lib/dropdown-item'>;
}
declare module 'element-ui/lib/dropdown-menu.js' {
  declare module.exports: $Exports<'element-ui/lib/dropdown-menu'>;
}
declare module 'element-ui/lib/dropdown.js' {
  declare module.exports: $Exports<'element-ui/lib/dropdown'>;
}
declare module 'element-ui/lib/element-ui.common.js' {
  declare module.exports: $Exports<'element-ui/lib/element-ui.common'>;
}
declare module 'element-ui/lib/form-item.js' {
  declare module.exports: $Exports<'element-ui/lib/form-item'>;
}
declare module 'element-ui/lib/form.js' {
  declare module.exports: $Exports<'element-ui/lib/form'>;
}
declare module 'element-ui/lib/icon.js' {
  declare module.exports: $Exports<'element-ui/lib/icon'>;
}
declare module 'element-ui/lib/index.js' {
  declare module.exports: $Exports<'element-ui/lib/index'>;
}
declare module 'element-ui/lib/input-number.js' {
  declare module.exports: $Exports<'element-ui/lib/input-number'>;
}
declare module 'element-ui/lib/input.js' {
  declare module.exports: $Exports<'element-ui/lib/input'>;
}
declare module 'element-ui/lib/loading.js' {
  declare module.exports: $Exports<'element-ui/lib/loading'>;
}
declare module 'element-ui/lib/locale/format.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/format'>;
}
declare module 'element-ui/lib/locale/index.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/index'>;
}
declare module 'element-ui/lib/locale/lang/af-ZA.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/af-ZA'>;
}
declare module 'element-ui/lib/locale/lang/ar.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/ar'>;
}
declare module 'element-ui/lib/locale/lang/bg.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/bg'>;
}
declare module 'element-ui/lib/locale/lang/ca.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/ca'>;
}
declare module 'element-ui/lib/locale/lang/cz.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/cz'>;
}
declare module 'element-ui/lib/locale/lang/da.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/da'>;
}
declare module 'element-ui/lib/locale/lang/de.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/de'>;
}
declare module 'element-ui/lib/locale/lang/ee.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/ee'>;
}
declare module 'element-ui/lib/locale/lang/el.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/el'>;
}
declare module 'element-ui/lib/locale/lang/en.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/en'>;
}
declare module 'element-ui/lib/locale/lang/es.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/es'>;
}
declare module 'element-ui/lib/locale/lang/fa.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/fa'>;
}
declare module 'element-ui/lib/locale/lang/fi.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/fi'>;
}
declare module 'element-ui/lib/locale/lang/fr.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/fr'>;
}
declare module 'element-ui/lib/locale/lang/id.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/id'>;
}
declare module 'element-ui/lib/locale/lang/it.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/it'>;
}
declare module 'element-ui/lib/locale/lang/ja.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/ja'>;
}
declare module 'element-ui/lib/locale/lang/ko.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/ko'>;
}
declare module 'element-ui/lib/locale/lang/lv.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/lv'>;
}
declare module 'element-ui/lib/locale/lang/nb-NO.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/nb-NO'>;
}
declare module 'element-ui/lib/locale/lang/nl.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/nl'>;
}
declare module 'element-ui/lib/locale/lang/pl.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/pl'>;
}
declare module 'element-ui/lib/locale/lang/pt-br.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/pt-br'>;
}
declare module 'element-ui/lib/locale/lang/pt.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/pt'>;
}
declare module 'element-ui/lib/locale/lang/ru-RU.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/ru-RU'>;
}
declare module 'element-ui/lib/locale/lang/sk.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/sk'>;
}
declare module 'element-ui/lib/locale/lang/sl.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/sl'>;
}
declare module 'element-ui/lib/locale/lang/sv-SE.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/sv-SE'>;
}
declare module 'element-ui/lib/locale/lang/ta.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/ta'>;
}
declare module 'element-ui/lib/locale/lang/th.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/th'>;
}
declare module 'element-ui/lib/locale/lang/tk.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/tk'>;
}
declare module 'element-ui/lib/locale/lang/tr-TR.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/tr-TR'>;
}
declare module 'element-ui/lib/locale/lang/ua.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/ua'>;
}
declare module 'element-ui/lib/locale/lang/vi.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/vi'>;
}
declare module 'element-ui/lib/locale/lang/zh-CN.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/zh-CN'>;
}
declare module 'element-ui/lib/locale/lang/zh-TW.js' {
  declare module.exports: $Exports<'element-ui/lib/locale/lang/zh-TW'>;
}
declare module 'element-ui/lib/menu-item-group.js' {
  declare module.exports: $Exports<'element-ui/lib/menu-item-group'>;
}
declare module 'element-ui/lib/menu-item.js' {
  declare module.exports: $Exports<'element-ui/lib/menu-item'>;
}
declare module 'element-ui/lib/menu.js' {
  declare module.exports: $Exports<'element-ui/lib/menu'>;
}
declare module 'element-ui/lib/message-box.js' {
  declare module.exports: $Exports<'element-ui/lib/message-box'>;
}
declare module 'element-ui/lib/message.js' {
  declare module.exports: $Exports<'element-ui/lib/message'>;
}
declare module 'element-ui/lib/mixins/emitter.js' {
  declare module.exports: $Exports<'element-ui/lib/mixins/emitter'>;
}
declare module 'element-ui/lib/mixins/locale.js' {
  declare module.exports: $Exports<'element-ui/lib/mixins/locale'>;
}
declare module 'element-ui/lib/mixins/migrating.js' {
  declare module.exports: $Exports<'element-ui/lib/mixins/migrating'>;
}
declare module 'element-ui/lib/notification.js' {
  declare module.exports: $Exports<'element-ui/lib/notification'>;
}
declare module 'element-ui/lib/option-group.js' {
  declare module.exports: $Exports<'element-ui/lib/option-group'>;
}
declare module 'element-ui/lib/option.js' {
  declare module.exports: $Exports<'element-ui/lib/option'>;
}
declare module 'element-ui/lib/pagination.js' {
  declare module.exports: $Exports<'element-ui/lib/pagination'>;
}
declare module 'element-ui/lib/popover.js' {
  declare module.exports: $Exports<'element-ui/lib/popover'>;
}
declare module 'element-ui/lib/progress.js' {
  declare module.exports: $Exports<'element-ui/lib/progress'>;
}
declare module 'element-ui/lib/radio-button.js' {
  declare module.exports: $Exports<'element-ui/lib/radio-button'>;
}
declare module 'element-ui/lib/radio-group.js' {
  declare module.exports: $Exports<'element-ui/lib/radio-group'>;
}
declare module 'element-ui/lib/radio.js' {
  declare module.exports: $Exports<'element-ui/lib/radio'>;
}
declare module 'element-ui/lib/rate.js' {
  declare module.exports: $Exports<'element-ui/lib/rate'>;
}
declare module 'element-ui/lib/row.js' {
  declare module.exports: $Exports<'element-ui/lib/row'>;
}
declare module 'element-ui/lib/scrollbar.js' {
  declare module.exports: $Exports<'element-ui/lib/scrollbar'>;
}
declare module 'element-ui/lib/select.js' {
  declare module.exports: $Exports<'element-ui/lib/select'>;
}
declare module 'element-ui/lib/slider.js' {
  declare module.exports: $Exports<'element-ui/lib/slider'>;
}
declare module 'element-ui/lib/spinner.js' {
  declare module.exports: $Exports<'element-ui/lib/spinner'>;
}
declare module 'element-ui/lib/step.js' {
  declare module.exports: $Exports<'element-ui/lib/step'>;
}
declare module 'element-ui/lib/steps.js' {
  declare module.exports: $Exports<'element-ui/lib/steps'>;
}
declare module 'element-ui/lib/submenu.js' {
  declare module.exports: $Exports<'element-ui/lib/submenu'>;
}
declare module 'element-ui/lib/switch.js' {
  declare module.exports: $Exports<'element-ui/lib/switch'>;
}
declare module 'element-ui/lib/tab-pane.js' {
  declare module.exports: $Exports<'element-ui/lib/tab-pane'>;
}
declare module 'element-ui/lib/table-column.js' {
  declare module.exports: $Exports<'element-ui/lib/table-column'>;
}
declare module 'element-ui/lib/table.js' {
  declare module.exports: $Exports<'element-ui/lib/table'>;
}
declare module 'element-ui/lib/tabs.js' {
  declare module.exports: $Exports<'element-ui/lib/tabs'>;
}
declare module 'element-ui/lib/tag.js' {
  declare module.exports: $Exports<'element-ui/lib/tag'>;
}
declare module 'element-ui/lib/time-picker.js' {
  declare module.exports: $Exports<'element-ui/lib/time-picker'>;
}
declare module 'element-ui/lib/time-select.js' {
  declare module.exports: $Exports<'element-ui/lib/time-select'>;
}
declare module 'element-ui/lib/tooltip.js' {
  declare module.exports: $Exports<'element-ui/lib/tooltip'>;
}
declare module 'element-ui/lib/transfer.js' {
  declare module.exports: $Exports<'element-ui/lib/transfer'>;
}
declare module 'element-ui/lib/transitions/collapse-transition.js' {
  declare module.exports: $Exports<'element-ui/lib/transitions/collapse-transition'>;
}
declare module 'element-ui/lib/tree.js' {
  declare module.exports: $Exports<'element-ui/lib/tree'>;
}
declare module 'element-ui/lib/umd/locale/af-ZA.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/af-ZA'>;
}
declare module 'element-ui/lib/umd/locale/ar.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/ar'>;
}
declare module 'element-ui/lib/umd/locale/bg.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/bg'>;
}
declare module 'element-ui/lib/umd/locale/ca.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/ca'>;
}
declare module 'element-ui/lib/umd/locale/cz.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/cz'>;
}
declare module 'element-ui/lib/umd/locale/da.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/da'>;
}
declare module 'element-ui/lib/umd/locale/de.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/de'>;
}
declare module 'element-ui/lib/umd/locale/ee.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/ee'>;
}
declare module 'element-ui/lib/umd/locale/el.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/el'>;
}
declare module 'element-ui/lib/umd/locale/en.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/en'>;
}
declare module 'element-ui/lib/umd/locale/es.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/es'>;
}
declare module 'element-ui/lib/umd/locale/fa.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/fa'>;
}
declare module 'element-ui/lib/umd/locale/fi.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/fi'>;
}
declare module 'element-ui/lib/umd/locale/fr.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/fr'>;
}
declare module 'element-ui/lib/umd/locale/id.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/id'>;
}
declare module 'element-ui/lib/umd/locale/it.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/it'>;
}
declare module 'element-ui/lib/umd/locale/ja.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/ja'>;
}
declare module 'element-ui/lib/umd/locale/ko.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/ko'>;
}
declare module 'element-ui/lib/umd/locale/lv.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/lv'>;
}
declare module 'element-ui/lib/umd/locale/nb-NO.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/nb-NO'>;
}
declare module 'element-ui/lib/umd/locale/nl.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/nl'>;
}
declare module 'element-ui/lib/umd/locale/pl.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/pl'>;
}
declare module 'element-ui/lib/umd/locale/pt-br.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/pt-br'>;
}
declare module 'element-ui/lib/umd/locale/pt.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/pt'>;
}
declare module 'element-ui/lib/umd/locale/ru-RU.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/ru-RU'>;
}
declare module 'element-ui/lib/umd/locale/sk.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/sk'>;
}
declare module 'element-ui/lib/umd/locale/sl.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/sl'>;
}
declare module 'element-ui/lib/umd/locale/sv-SE.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/sv-SE'>;
}
declare module 'element-ui/lib/umd/locale/ta.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/ta'>;
}
declare module 'element-ui/lib/umd/locale/th.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/th'>;
}
declare module 'element-ui/lib/umd/locale/tk.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/tk'>;
}
declare module 'element-ui/lib/umd/locale/tr-TR.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/tr-TR'>;
}
declare module 'element-ui/lib/umd/locale/ua.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/ua'>;
}
declare module 'element-ui/lib/umd/locale/vi.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/vi'>;
}
declare module 'element-ui/lib/umd/locale/zh-CN.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/zh-CN'>;
}
declare module 'element-ui/lib/umd/locale/zh-TW.js' {
  declare module.exports: $Exports<'element-ui/lib/umd/locale/zh-TW'>;
}
declare module 'element-ui/lib/upload.js' {
  declare module.exports: $Exports<'element-ui/lib/upload'>;
}
declare module 'element-ui/lib/utils/clickoutside.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/clickoutside'>;
}
declare module 'element-ui/lib/utils/date.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/date'>;
}
declare module 'element-ui/lib/utils/dom.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/dom'>;
}
declare module 'element-ui/lib/utils/merge.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/merge'>;
}
declare module 'element-ui/lib/utils/popper.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/popper'>;
}
declare module 'element-ui/lib/utils/popup/index.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/popup/index'>;
}
declare module 'element-ui/lib/utils/popup/popup-manager.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/popup/popup-manager'>;
}
declare module 'element-ui/lib/utils/resize-event.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/resize-event'>;
}
declare module 'element-ui/lib/utils/scroll-into-view.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/scroll-into-view'>;
}
declare module 'element-ui/lib/utils/scrollbar-width.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/scrollbar-width'>;
}
declare module 'element-ui/lib/utils/shared.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/shared'>;
}
declare module 'element-ui/lib/utils/sync.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/sync'>;
}
declare module 'element-ui/lib/utils/util.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/util'>;
}
declare module 'element-ui/lib/utils/vdom.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/vdom'>;
}
declare module 'element-ui/lib/utils/vue-popper.js' {
  declare module.exports: $Exports<'element-ui/lib/utils/vue-popper'>;
}
declare module 'element-ui/packages/alert/index.js' {
  declare module.exports: $Exports<'element-ui/packages/alert/index'>;
}
declare module 'element-ui/packages/autocomplete/index.js' {
  declare module.exports: $Exports<'element-ui/packages/autocomplete/index'>;
}
declare module 'element-ui/packages/badge/index.js' {
  declare module.exports: $Exports<'element-ui/packages/badge/index'>;
}
declare module 'element-ui/packages/breadcrumb-item/index.js' {
  declare module.exports: $Exports<'element-ui/packages/breadcrumb-item/index'>;
}
declare module 'element-ui/packages/breadcrumb/index.js' {
  declare module.exports: $Exports<'element-ui/packages/breadcrumb/index'>;
}
declare module 'element-ui/packages/button-group/index.js' {
  declare module.exports: $Exports<'element-ui/packages/button-group/index'>;
}
declare module 'element-ui/packages/button/index.js' {
  declare module.exports: $Exports<'element-ui/packages/button/index'>;
}
declare module 'element-ui/packages/card/index.js' {
  declare module.exports: $Exports<'element-ui/packages/card/index'>;
}
declare module 'element-ui/packages/carousel-item/index.js' {
  declare module.exports: $Exports<'element-ui/packages/carousel-item/index'>;
}
declare module 'element-ui/packages/carousel/_index.js' {
  declare module.exports: $Exports<'element-ui/packages/carousel/_index'>;
}
declare module 'element-ui/packages/carousel/cooking.conf.js' {
  declare module.exports: $Exports<'element-ui/packages/carousel/cooking.conf'>;
}
declare module 'element-ui/packages/carousel/index.js' {
  declare module.exports: $Exports<'element-ui/packages/carousel/index'>;
}
declare module 'element-ui/packages/cascader/cooking.conf.js' {
  declare module.exports: $Exports<'element-ui/packages/cascader/cooking.conf'>;
}
declare module 'element-ui/packages/cascader/index.js' {
  declare module.exports: $Exports<'element-ui/packages/cascader/index'>;
}
declare module 'element-ui/packages/checkbox-button/index.js' {
  declare module.exports: $Exports<'element-ui/packages/checkbox-button/index'>;
}
declare module 'element-ui/packages/checkbox-group/index.js' {
  declare module.exports: $Exports<'element-ui/packages/checkbox-group/index'>;
}
declare module 'element-ui/packages/checkbox/index.js' {
  declare module.exports: $Exports<'element-ui/packages/checkbox/index'>;
}
declare module 'element-ui/packages/col/index.js' {
  declare module.exports: $Exports<'element-ui/packages/col/index'>;
}
declare module 'element-ui/packages/col/src/col.js' {
  declare module.exports: $Exports<'element-ui/packages/col/src/col'>;
}
declare module 'element-ui/packages/collapse-item/index.js' {
  declare module.exports: $Exports<'element-ui/packages/collapse-item/index'>;
}
declare module 'element-ui/packages/collapse/index.js' {
  declare module.exports: $Exports<'element-ui/packages/collapse/index'>;
}
declare module 'element-ui/packages/color-picker/cooking.conf.js' {
  declare module.exports: $Exports<'element-ui/packages/color-picker/cooking.conf'>;
}
declare module 'element-ui/packages/color-picker/index.js' {
  declare module.exports: $Exports<'element-ui/packages/color-picker/index'>;
}
declare module 'element-ui/packages/color-picker/src/color.js' {
  declare module.exports: $Exports<'element-ui/packages/color-picker/src/color'>;
}
declare module 'element-ui/packages/color-picker/src/draggable.js' {
  declare module.exports: $Exports<'element-ui/packages/color-picker/src/draggable'>;
}
declare module 'element-ui/packages/date-picker/_index.js' {
  declare module.exports: $Exports<'element-ui/packages/date-picker/_index'>;
}
declare module 'element-ui/packages/date-picker/cooking.conf.js' {
  declare module.exports: $Exports<'element-ui/packages/date-picker/cooking.conf'>;
}
declare module 'element-ui/packages/date-picker/index.js' {
  declare module.exports: $Exports<'element-ui/packages/date-picker/index'>;
}
declare module 'element-ui/packages/date-picker/src/picker/date-picker.js' {
  declare module.exports: $Exports<'element-ui/packages/date-picker/src/picker/date-picker'>;
}
declare module 'element-ui/packages/date-picker/src/picker/time-picker.js' {
  declare module.exports: $Exports<'element-ui/packages/date-picker/src/picker/time-picker'>;
}
declare module 'element-ui/packages/date-picker/src/picker/time-select.js' {
  declare module.exports: $Exports<'element-ui/packages/date-picker/src/picker/time-select'>;
}
declare module 'element-ui/packages/date-picker/src/util/index.js' {
  declare module.exports: $Exports<'element-ui/packages/date-picker/src/util/index'>;
}
declare module 'element-ui/packages/dialog/index.js' {
  declare module.exports: $Exports<'element-ui/packages/dialog/index'>;
}
declare module 'element-ui/packages/dropdown-item/index.js' {
  declare module.exports: $Exports<'element-ui/packages/dropdown-item/index'>;
}
declare module 'element-ui/packages/dropdown-menu/index.js' {
  declare module.exports: $Exports<'element-ui/packages/dropdown-menu/index'>;
}
declare module 'element-ui/packages/dropdown/index.js' {
  declare module.exports: $Exports<'element-ui/packages/dropdown/index'>;
}
declare module 'element-ui/packages/form-item/index.js' {
  declare module.exports: $Exports<'element-ui/packages/form-item/index'>;
}
declare module 'element-ui/packages/form/index.js' {
  declare module.exports: $Exports<'element-ui/packages/form/index'>;
}
declare module 'element-ui/packages/icon/index.js' {
  declare module.exports: $Exports<'element-ui/packages/icon/index'>;
}
declare module 'element-ui/packages/input-number/index.js' {
  declare module.exports: $Exports<'element-ui/packages/input-number/index'>;
}
declare module 'element-ui/packages/input/index.js' {
  declare module.exports: $Exports<'element-ui/packages/input/index'>;
}
declare module 'element-ui/packages/input/src/calcTextareaHeight.js' {
  declare module.exports: $Exports<'element-ui/packages/input/src/calcTextareaHeight'>;
}
declare module 'element-ui/packages/loading/cooking.conf.js' {
  declare module.exports: $Exports<'element-ui/packages/loading/cooking.conf'>;
}
declare module 'element-ui/packages/loading/index.js' {
  declare module.exports: $Exports<'element-ui/packages/loading/index'>;
}
declare module 'element-ui/packages/loading/src/directive.js' {
  declare module.exports: $Exports<'element-ui/packages/loading/src/directive'>;
}
declare module 'element-ui/packages/loading/src/index.js' {
  declare module.exports: $Exports<'element-ui/packages/loading/src/index'>;
}
declare module 'element-ui/packages/menu-item-group/index.js' {
  declare module.exports: $Exports<'element-ui/packages/menu-item-group/index'>;
}
declare module 'element-ui/packages/menu-item/index.js' {
  declare module.exports: $Exports<'element-ui/packages/menu-item/index'>;
}
declare module 'element-ui/packages/menu/index.js' {
  declare module.exports: $Exports<'element-ui/packages/menu/index'>;
}
declare module 'element-ui/packages/menu/src/menu-mixin.js' {
  declare module.exports: $Exports<'element-ui/packages/menu/src/menu-mixin'>;
}
declare module 'element-ui/packages/message-box/index.js' {
  declare module.exports: $Exports<'element-ui/packages/message-box/index'>;
}
declare module 'element-ui/packages/message-box/src/main.js' {
  declare module.exports: $Exports<'element-ui/packages/message-box/src/main'>;
}
declare module 'element-ui/packages/message/index.js' {
  declare module.exports: $Exports<'element-ui/packages/message/index'>;
}
declare module 'element-ui/packages/message/src/main.js' {
  declare module.exports: $Exports<'element-ui/packages/message/src/main'>;
}
declare module 'element-ui/packages/notification/index.js' {
  declare module.exports: $Exports<'element-ui/packages/notification/index'>;
}
declare module 'element-ui/packages/notification/src/main.js' {
  declare module.exports: $Exports<'element-ui/packages/notification/src/main'>;
}
declare module 'element-ui/packages/option-group/index.js' {
  declare module.exports: $Exports<'element-ui/packages/option-group/index'>;
}
declare module 'element-ui/packages/option/index.js' {
  declare module.exports: $Exports<'element-ui/packages/option/index'>;
}
declare module 'element-ui/packages/pagination/cooking.conf.js' {
  declare module.exports: $Exports<'element-ui/packages/pagination/cooking.conf'>;
}
declare module 'element-ui/packages/pagination/index.js' {
  declare module.exports: $Exports<'element-ui/packages/pagination/index'>;
}
declare module 'element-ui/packages/pagination/src/pagination.js' {
  declare module.exports: $Exports<'element-ui/packages/pagination/src/pagination'>;
}
declare module 'element-ui/packages/popover/index.js' {
  declare module.exports: $Exports<'element-ui/packages/popover/index'>;
}
declare module 'element-ui/packages/popover/src/directive.js' {
  declare module.exports: $Exports<'element-ui/packages/popover/src/directive'>;
}
declare module 'element-ui/packages/progress/index.js' {
  declare module.exports: $Exports<'element-ui/packages/progress/index'>;
}
declare module 'element-ui/packages/radio-button/index.js' {
  declare module.exports: $Exports<'element-ui/packages/radio-button/index'>;
}
declare module 'element-ui/packages/radio-group/index.js' {
  declare module.exports: $Exports<'element-ui/packages/radio-group/index'>;
}
declare module 'element-ui/packages/radio/index.js' {
  declare module.exports: $Exports<'element-ui/packages/radio/index'>;
}
declare module 'element-ui/packages/rate/index.js' {
  declare module.exports: $Exports<'element-ui/packages/rate/index'>;
}
declare module 'element-ui/packages/row/index.js' {
  declare module.exports: $Exports<'element-ui/packages/row/index'>;
}
declare module 'element-ui/packages/row/src/row.js' {
  declare module.exports: $Exports<'element-ui/packages/row/src/row'>;
}
declare module 'element-ui/packages/scrollbar/index.js' {
  declare module.exports: $Exports<'element-ui/packages/scrollbar/index'>;
}
declare module 'element-ui/packages/scrollbar/src/bar.js' {
  declare module.exports: $Exports<'element-ui/packages/scrollbar/src/bar'>;
}
declare module 'element-ui/packages/scrollbar/src/main.js' {
  declare module.exports: $Exports<'element-ui/packages/scrollbar/src/main'>;
}
declare module 'element-ui/packages/scrollbar/src/util.js' {
  declare module.exports: $Exports<'element-ui/packages/scrollbar/src/util'>;
}
declare module 'element-ui/packages/select/index.js' {
  declare module.exports: $Exports<'element-ui/packages/select/index'>;
}
declare module 'element-ui/packages/slider/index.js' {
  declare module.exports: $Exports<'element-ui/packages/slider/index'>;
}
declare module 'element-ui/packages/spinner/index.js' {
  declare module.exports: $Exports<'element-ui/packages/spinner/index'>;
}
declare module 'element-ui/packages/step/index.js' {
  declare module.exports: $Exports<'element-ui/packages/step/index'>;
}
declare module 'element-ui/packages/steps/index.js' {
  declare module.exports: $Exports<'element-ui/packages/steps/index'>;
}
declare module 'element-ui/packages/submenu/index.js' {
  declare module.exports: $Exports<'element-ui/packages/submenu/index'>;
}
declare module 'element-ui/packages/switch/index.js' {
  declare module.exports: $Exports<'element-ui/packages/switch/index'>;
}
declare module 'element-ui/packages/tab-pane/index.js' {
  declare module.exports: $Exports<'element-ui/packages/tab-pane/index'>;
}
declare module 'element-ui/packages/table-column/index.js' {
  declare module.exports: $Exports<'element-ui/packages/table-column/index'>;
}
declare module 'element-ui/packages/table/_index.js' {
  declare module.exports: $Exports<'element-ui/packages/table/_index'>;
}
declare module 'element-ui/packages/table/cooking.conf.js' {
  declare module.exports: $Exports<'element-ui/packages/table/cooking.conf'>;
}
declare module 'element-ui/packages/table/index.js' {
  declare module.exports: $Exports<'element-ui/packages/table/index'>;
}
declare module 'element-ui/packages/table/src/dropdown.js' {
  declare module.exports: $Exports<'element-ui/packages/table/src/dropdown'>;
}
declare module 'element-ui/packages/table/src/table-body.js' {
  declare module.exports: $Exports<'element-ui/packages/table/src/table-body'>;
}
declare module 'element-ui/packages/table/src/table-column.js' {
  declare module.exports: $Exports<'element-ui/packages/table/src/table-column'>;
}
declare module 'element-ui/packages/table/src/table-footer.js' {
  declare module.exports: $Exports<'element-ui/packages/table/src/table-footer'>;
}
declare module 'element-ui/packages/table/src/table-header.js' {
  declare module.exports: $Exports<'element-ui/packages/table/src/table-header'>;
}
declare module 'element-ui/packages/table/src/table-layout.js' {
  declare module.exports: $Exports<'element-ui/packages/table/src/table-layout'>;
}
declare module 'element-ui/packages/table/src/table-store.js' {
  declare module.exports: $Exports<'element-ui/packages/table/src/table-store'>;
}
declare module 'element-ui/packages/table/src/util.js' {
  declare module.exports: $Exports<'element-ui/packages/table/src/util'>;
}
declare module 'element-ui/packages/tabs/index.js' {
  declare module.exports: $Exports<'element-ui/packages/tabs/index'>;
}
declare module 'element-ui/packages/tag/index.js' {
  declare module.exports: $Exports<'element-ui/packages/tag/index'>;
}
declare module 'element-ui/packages/time-picker/index.js' {
  declare module.exports: $Exports<'element-ui/packages/time-picker/index'>;
}
declare module 'element-ui/packages/time-select/index.js' {
  declare module.exports: $Exports<'element-ui/packages/time-select/index'>;
}
declare module 'element-ui/packages/tooltip/index.js' {
  declare module.exports: $Exports<'element-ui/packages/tooltip/index'>;
}
declare module 'element-ui/packages/tooltip/src/main.js' {
  declare module.exports: $Exports<'element-ui/packages/tooltip/src/main'>;
}
declare module 'element-ui/packages/transfer/index.js' {
  declare module.exports: $Exports<'element-ui/packages/transfer/index'>;
}
declare module 'element-ui/packages/tree/index.js' {
  declare module.exports: $Exports<'element-ui/packages/tree/index'>;
}
declare module 'element-ui/packages/tree/src/model/node.js' {
  declare module.exports: $Exports<'element-ui/packages/tree/src/model/node'>;
}
declare module 'element-ui/packages/tree/src/model/tree-store.js' {
  declare module.exports: $Exports<'element-ui/packages/tree/src/model/tree-store'>;
}
declare module 'element-ui/packages/tree/src/model/util.js' {
  declare module.exports: $Exports<'element-ui/packages/tree/src/model/util'>;
}
declare module 'element-ui/packages/upload/cooking.conf.js' {
  declare module.exports: $Exports<'element-ui/packages/upload/cooking.conf'>;
}
declare module 'element-ui/packages/upload/index.js' {
  declare module.exports: $Exports<'element-ui/packages/upload/index'>;
}
declare module 'element-ui/packages/upload/src/ajax.js' {
  declare module.exports: $Exports<'element-ui/packages/upload/src/ajax'>;
}
declare module 'element-ui/src/index.js' {
  declare module.exports: $Exports<'element-ui/src/index'>;
}
declare module 'element-ui/src/locale/format.js' {
  declare module.exports: $Exports<'element-ui/src/locale/format'>;
}
declare module 'element-ui/src/locale/index.js' {
  declare module.exports: $Exports<'element-ui/src/locale/index'>;
}
declare module 'element-ui/src/locale/lang/af-ZA.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/af-ZA'>;
}
declare module 'element-ui/src/locale/lang/ar.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/ar'>;
}
declare module 'element-ui/src/locale/lang/bg.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/bg'>;
}
declare module 'element-ui/src/locale/lang/ca.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/ca'>;
}
declare module 'element-ui/src/locale/lang/cz.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/cz'>;
}
declare module 'element-ui/src/locale/lang/da.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/da'>;
}
declare module 'element-ui/src/locale/lang/de.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/de'>;
}
declare module 'element-ui/src/locale/lang/ee.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/ee'>;
}
declare module 'element-ui/src/locale/lang/el.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/el'>;
}
declare module 'element-ui/src/locale/lang/en.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/en'>;
}
declare module 'element-ui/src/locale/lang/es.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/es'>;
}
declare module 'element-ui/src/locale/lang/fa.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/fa'>;
}
declare module 'element-ui/src/locale/lang/fi.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/fi'>;
}
declare module 'element-ui/src/locale/lang/fr.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/fr'>;
}
declare module 'element-ui/src/locale/lang/id.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/id'>;
}
declare module 'element-ui/src/locale/lang/it.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/it'>;
}
declare module 'element-ui/src/locale/lang/ja.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/ja'>;
}
declare module 'element-ui/src/locale/lang/ko.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/ko'>;
}
declare module 'element-ui/src/locale/lang/lv.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/lv'>;
}
declare module 'element-ui/src/locale/lang/nb-NO.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/nb-NO'>;
}
declare module 'element-ui/src/locale/lang/nl.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/nl'>;
}
declare module 'element-ui/src/locale/lang/pl.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/pl'>;
}
declare module 'element-ui/src/locale/lang/pt-br.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/pt-br'>;
}
declare module 'element-ui/src/locale/lang/pt.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/pt'>;
}
declare module 'element-ui/src/locale/lang/ru-RU.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/ru-RU'>;
}
declare module 'element-ui/src/locale/lang/sk.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/sk'>;
}
declare module 'element-ui/src/locale/lang/sl.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/sl'>;
}
declare module 'element-ui/src/locale/lang/sv-SE.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/sv-SE'>;
}
declare module 'element-ui/src/locale/lang/ta.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/ta'>;
}
declare module 'element-ui/src/locale/lang/th.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/th'>;
}
declare module 'element-ui/src/locale/lang/tk.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/tk'>;
}
declare module 'element-ui/src/locale/lang/tr-TR.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/tr-TR'>;
}
declare module 'element-ui/src/locale/lang/ua.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/ua'>;
}
declare module 'element-ui/src/locale/lang/vi.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/vi'>;
}
declare module 'element-ui/src/locale/lang/zh-CN.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/zh-CN'>;
}
declare module 'element-ui/src/locale/lang/zh-TW.js' {
  declare module.exports: $Exports<'element-ui/src/locale/lang/zh-TW'>;
}
declare module 'element-ui/src/mixins/emitter.js' {
  declare module.exports: $Exports<'element-ui/src/mixins/emitter'>;
}
declare module 'element-ui/src/mixins/locale.js' {
  declare module.exports: $Exports<'element-ui/src/mixins/locale'>;
}
declare module 'element-ui/src/mixins/migrating.js' {
  declare module.exports: $Exports<'element-ui/src/mixins/migrating'>;
}
declare module 'element-ui/src/transitions/collapse-transition.js' {
  declare module.exports: $Exports<'element-ui/src/transitions/collapse-transition'>;
}
declare module 'element-ui/src/utils/clickoutside.js' {
  declare module.exports: $Exports<'element-ui/src/utils/clickoutside'>;
}
declare module 'element-ui/src/utils/date.js' {
  declare module.exports: $Exports<'element-ui/src/utils/date'>;
}
declare module 'element-ui/src/utils/dom.js' {
  declare module.exports: $Exports<'element-ui/src/utils/dom'>;
}
declare module 'element-ui/src/utils/merge.js' {
  declare module.exports: $Exports<'element-ui/src/utils/merge'>;
}
declare module 'element-ui/src/utils/popper.js' {
  declare module.exports: $Exports<'element-ui/src/utils/popper'>;
}
declare module 'element-ui/src/utils/popup/index.js' {
  declare module.exports: $Exports<'element-ui/src/utils/popup/index'>;
}
declare module 'element-ui/src/utils/popup/popup-manager.js' {
  declare module.exports: $Exports<'element-ui/src/utils/popup/popup-manager'>;
}
declare module 'element-ui/src/utils/resize-event.js' {
  declare module.exports: $Exports<'element-ui/src/utils/resize-event'>;
}
declare module 'element-ui/src/utils/scroll-into-view.js' {
  declare module.exports: $Exports<'element-ui/src/utils/scroll-into-view'>;
}
declare module 'element-ui/src/utils/scrollbar-width.js' {
  declare module.exports: $Exports<'element-ui/src/utils/scrollbar-width'>;
}
declare module 'element-ui/src/utils/shared.js' {
  declare module.exports: $Exports<'element-ui/src/utils/shared'>;
}
declare module 'element-ui/src/utils/sync.js' {
  declare module.exports: $Exports<'element-ui/src/utils/sync'>;
}
declare module 'element-ui/src/utils/util.js' {
  declare module.exports: $Exports<'element-ui/src/utils/util'>;
}
declare module 'element-ui/src/utils/vdom.js' {
  declare module.exports: $Exports<'element-ui/src/utils/vdom'>;
}
declare module 'element-ui/src/utils/vue-popper.js' {
  declare module.exports: $Exports<'element-ui/src/utils/vue-popper'>;
}
