// flow-typed signature: 0cf57f84c782a9ee962681726baba3f7
// flow-typed version: <<STUB>>/karma-spec-reporter_v0.0.31/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-spec-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-spec-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-spec-reporter/index' {
  declare module.exports: $Exports<'karma-spec-reporter'>;
}
declare module 'karma-spec-reporter/index.js' {
  declare module.exports: $Exports<'karma-spec-reporter'>;
}
