# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: calculator.proto for package ''

require 'grpc'
require 'calculator_pb'

module Calculator
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Calculator'

    rpc :Calculate, CalculatorRequest, CalculatorResponse
  end

  Stub = Service.rpc_stub_class
end
