# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: greeter.proto for package ''

require 'grpc'
require 'greeter_pb'

module Greeter
  # The greeter service definition.
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Greeter'

    # Sends a greeting
    rpc :SayHello, HelloRequest, HelloReply
  end

  Stub = Service.rpc_stub_class
end
